# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blasterQt.ui'
#
# Created: Mon Apr 15 16:12:42 2019
#      by: pyside2-uic  running on PySide2 5.6.0a1.dev1528216830
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_BLASTER_WINDOW(object):
    def setupUi(self, BLASTER_WINDOW):
        BLASTER_WINDOW.setObjectName("BLASTER_WINDOW")
        BLASTER_WINDOW.resize(537, 216)
        self.centralwidget = QtWidgets.QWidget(BLASTER_WINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.let_output = QtWidgets.QLineEdit(self.centralwidget)
        self.let_output.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.let_output.setFont(font)
        self.let_output.setObjectName("let_output")
        self.horizontalLayout_5.addWidget(self.let_output)
        self.btn_setoutputpath = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setoutputpath.setMinimumSize(QtCore.QSize(40, 25))
        self.btn_setoutputpath.setMaximumSize(QtCore.QSize(40, 25))
        self.btn_setoutputpath.setObjectName("btn_setoutputpath")
        self.horizontalLayout_5.addWidget(self.btn_setoutputpath)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.let_videoname = QtWidgets.QLineEdit(self.centralwidget)
        self.let_videoname.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.let_videoname.setFont(font)
        self.let_videoname.setObjectName("let_videoname")
        self.horizontalLayout_7.addWidget(self.let_videoname)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.let_artist = QtWidgets.QLineEdit(self.centralwidget)
        self.let_artist.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.let_artist.setFont(font)
        self.let_artist.setObjectName("let_artist")
        self.horizontalLayout_4.addWidget(self.let_artist)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbx_updateversion = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbx_updateversion.setFont(font)
        self.cbx_updateversion.setChecked(True)
        self.cbx_updateversion.setObjectName("cbx_updateversion")
        self.horizontalLayout_2.addWidget(self.cbx_updateversion)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cbx_viewoutput = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbx_viewoutput.setFont(font)
        self.cbx_viewoutput.setChecked(True)
        self.cbx_viewoutput.setObjectName("cbx_viewoutput")
        self.horizontalLayout_6.addWidget(self.cbx_viewoutput)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.btn_playblast = QtWidgets.QPushButton(self.centralwidget)
        self.btn_playblast.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_playblast.setFont(font)
        self.btn_playblast.setObjectName("btn_playblast")
        self.horizontalLayout.addWidget(self.btn_playblast)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        BLASTER_WINDOW.setCentralWidget(self.centralwidget)

        self.retranslateUi(BLASTER_WINDOW)
        QtCore.QMetaObject.connectSlotsByName(BLASTER_WINDOW)

    def retranslateUi(self, BLASTER_WINDOW):
        BLASTER_WINDOW.setWindowTitle(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Playblast", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Output Path:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Video Name:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Artist:", None, -1))
        self.btn_setoutputpath.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "...", None, -1))
        self.cbx_updateversion.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Update Version", None, -1))
        self.cbx_viewoutput.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "View Output", None, -1))
        self.btn_playblast.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Playblast", None, -1))

