# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blasterQt.ui'
#
# Created: Mon Apr 29 16:09:55 2019
#      by: pyside2-uic  running on PySide2 5.6.0a1.dev1528216830
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_BLASTER_WINDOW(object):
    def setupUi(self, BLASTER_WINDOW):
        BLASTER_WINDOW.setObjectName("BLASTER_WINDOW")
        BLASTER_WINDOW.resize(633, 294)
        self.centralwidget = QtWidgets.QWidget(BLASTER_WINDOW)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName("gridLayout")
        self.let_output = QtWidgets.QLineEdit(self.centralwidget)
        self.let_output.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.let_output.setFont(font)
        self.let_output.setObjectName("let_output")
        self.gridLayout.addWidget(self.let_output, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_setoutputpath = QtWidgets.QPushButton(self.centralwidget)
        self.btn_setoutputpath.setMinimumSize(QtCore.QSize(40, 24))
        self.btn_setoutputpath.setMaximumSize(QtCore.QSize(40, 24))
        self.btn_setoutputpath.setObjectName("btn_setoutputpath")
        self.gridLayout.addWidget(self.btn_setoutputpath, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.let_videoname = QtWidgets.QLineEdit(self.centralwidget)
        self.let_videoname.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.let_videoname.setFont(font)
        self.let_videoname.setObjectName("let_videoname")
        self.gridLayout_2.addWidget(self.let_videoname, 0, 1, 1, 1)
        self.cbx_updateversion = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbx_updateversion.setFont(font)
        self.cbx_updateversion.setChecked(True)
        self.cbx_updateversion.setObjectName("cbx_updateversion")
        self.gridLayout_2.addWidget(self.cbx_updateversion, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.let_artist = QtWidgets.QLineEdit(self.centralwidget)
        self.let_artist.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.let_artist.setFont(font)
        self.let_artist.setObjectName("let_artist")
        self.gridLayout_3.addWidget(self.let_artist, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setHorizontalSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMinimumSize(QtCore.QSize(100, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_4.addWidget(self.radioButton, 0, 1, 1, 1)
        self.spx_endFrame = QtWidgets.QSpinBox(self.centralwidget)
        self.spx_endFrame.setEnabled(False)
        self.spx_endFrame.setMinimumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spx_endFrame.setFont(font)
        self.spx_endFrame.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spx_endFrame.setMinimum(-16777215)
        self.spx_endFrame.setMaximum(16777215)
        self.spx_endFrame.setProperty("value", 10)
        self.spx_endFrame.setObjectName("spx_endFrame")
        self.gridLayout_4.addWidget(self.spx_endFrame, 1, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 0, 5, 1, 1)
        self.spx_startFrame = QtWidgets.QSpinBox(self.centralwidget)
        self.spx_startFrame.setEnabled(False)
        self.spx_startFrame.setMinimumSize(QtCore.QSize(80, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spx_startFrame.setFont(font)
        self.spx_startFrame.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.spx_startFrame.setMinimum(-16777215)
        self.spx_startFrame.setMaximum(16777215)
        self.spx_startFrame.setObjectName("spx_startFrame")
        self.gridLayout_4.addWidget(self.spx_startFrame, 1, 3, 1, 1)
        self.rdn_frameByInput = QtWidgets.QRadioButton(self.centralwidget)
        self.rdn_frameByInput.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rdn_frameByInput.setFont(font)
        self.rdn_frameByInput.setObjectName("rdn_frameByInput")
        self.gridLayout_4.addWidget(self.rdn_frameByInput, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cbx_viewoutput = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cbx_viewoutput.setFont(font)
        self.cbx_viewoutput.setChecked(True)
        self.cbx_viewoutput.setObjectName("cbx_viewoutput")
        self.gridLayout_5.addWidget(self.cbx_viewoutput, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btn_playblast = QtWidgets.QPushButton(self.centralwidget)
        self.btn_playblast.setMinimumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_playblast.setFont(font)
        self.btn_playblast.setObjectName("btn_playblast")
        self.horizontalLayout.addWidget(self.btn_playblast)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        BLASTER_WINDOW.setCentralWidget(self.centralwidget)

        self.retranslateUi(BLASTER_WINDOW)
        QtCore.QObject.connect(self.rdn_frameByInput, QtCore.SIGNAL("toggled(bool)"), self.spx_startFrame.setEnabled)
        QtCore.QObject.connect(self.rdn_frameByInput, QtCore.SIGNAL("toggled(bool)"), self.spx_endFrame.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(BLASTER_WINDOW)

    def retranslateUi(self, BLASTER_WINDOW):
        BLASTER_WINDOW.setWindowTitle(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Playblast", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Output Path:", None, -1))
        self.btn_setoutputpath.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "...", None, -1))
        self.cbx_updateversion.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Update Version", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Video Name:", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Artist:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Time Range:", None, -1))
        self.radioButton.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "By TimeSlider", None, -1))
        self.rdn_frameByInput.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "By Input", None, -1))
        self.cbx_viewoutput.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "View Output", None, -1))
        self.btn_playblast.setText(QtWidgets.QApplication.translate("BLASTER_WINDOW", "Playblast", None, -1))

